[NEAT]

# Stop when one genome fitness reaches...
fitness_criterion     = mean
fitness_threshold     = 200

# Population size per genome
pop_size              = 50

# Complete all generations even if fitness condition is reached ?
no_fitness_termination = False

reset_on_extinction   = False


[DefaultGenome]
# Initial activation functions to use
activation_default      = sigmoid
# Possible activation functions to use
activation_options      = sigmoid,relu
# Rate at which activation function must be replaced during evolution. [0.0,1.0]
activation_mutate_rate  = 0.0

# network parameters
num_inputs              = 4
num_hidden              = 0
num_outputs             = 1

feed_forward            = False

# How to init nodes connection for a new genome ?
# unconnected = no connections between nodes
# full_direct = inputs are connected to hiddens AND outputs, and hiddens are also connected to outputs if any
# full_nodirect = inputs are connected to hiddens if any, and hiddens are also connected to outputs if any, but inputs are not connected to outputs diretcly
# partial_nodirect = same as full_nodirect but some nodes may or may not be connected depending on a weight value [0.0,1.0]. Usage: partial_nodirect 0.5
# partial_direct = same as full_direct but some nodes may or may not be connected depending on a weight value [0.0,1.0]. Usage: partial_nodirect 0.5
initial_connection      = full_direct


# node aggregation options
aggregation_default     = sum
aggregation_mutate_rate = 0.0
aggregation_options     = sum

# node bias options
bias_init_mean          = 0.0
bias_init_stdev         = 1.0
bias_max_value          = 30
bias_min_value          = -30
bias_mutate_power       = 0.5
bias_mutate_rate        = 0.7
bias_replace_rate       = 0.1

# genome compatibility options
compatibility_disjoint_coefficient = 1.0
compatibility_weight_coefficient   = 0.5

# connection add/remove rates
conn_add_prob           = 0.5
conn_delete_prob        = 0.5

# connection enable options
enabled_default         = True
enabled_mutate_rate     = 0.01


# node add/remove rates
node_add_prob           = 0.2
node_delete_prob        = 0.2


# node response options
response_init_mean      = 1.0
response_init_stdev     = 0.0
response_max_value      = 30.0
response_min_value      = -30.0
response_mutate_power   = 0.0
response_mutate_rate    = 0.0
response_replace_rate   = 0.0

# connection weight options
weight_init_mean        = 0.0
weight_init_stdev       = 1.0
weight_max_value        = 30
weight_min_value        = -30
weight_mutate_power     = 0.5
weight_mutate_rate      = 0.8
weight_replace_rate     = 0.1

[DefaultSpeciesSet]
compatibility_threshold = 3.0

[DefaultStagnation]
species_fitness_func = max
max_stagnation       = 20
species_elitism      = 2

[DefaultReproduction]
elitism            = 2
survival_threshold = 0.2